In [1]:
import gspread
import pandas as pd
import seaborn as sns
import matplotlib.pylab as plt
import datetime as dt
import numpy as np
from matplotlib.ticker import MaxNLocator

sa = gspread.service_account(
    filename="/Users/taylorcastillo/Documents/Python/keys/service_account.json")
sh = sa.open("Calorie Tracker")
wks = sh.worksheet("Form Responses 1")
df = pd.DataFrame(wks.get_all_records())
df = df.rename(columns = {"Timestamp":"Date"})
df_step1 = df

In [8]:
df = df_step1

# replace all blank values with null
for i in list(df.keys()):
    df[i] = df[i].replace('', np.nan)

# create dictionary to map columns to data types
remap_dtype = {
    "Date":"datetime64[ns]",
    "Weight":"float64",
    "Net Calories":"Int64",
    "Email Address":"category",
    "User":"category"
}

# recast data types
for i in list(remap_dtype.keys()):
    df[i] = df[i].astype(str(remap_dtype[i]))

# set the index to date and sort it
df = df.set_index(["Date","User"])
df = df.sort_index(ascending=False)
df = df.drop(["Email Address", "Hours Slept", "Steps"], axis=1)

In [14]:

df.head()

                             Weight  Net Calories
Date                User
2023-02-03 08:20:55 T-Money   288.2         -1000
2023-02-02 13:46:16 T-Money   288.6         -1000
2023-02-01 16:51:27 T-Money   297.8         -1000
2023-01-31 19:13:28 T-Money   288.8          1200
2023-01-30 08:57:35 T-Money   285.6             0

In [18]:
(
    df["Weight"]
        .add(10)
        .div(2)
)
df.head()

                             Weight  Net Calories
Date                User
2023-02-03 08:20:55 T-Money   288.2         -1000
2023-02-02 13:46:16 T-Money   288.6         -1000
2023-02-01 16:51:27 T-Money   297.8         -1000
2023-01-31 19:13:28 T-Money   288.8          1200
2023-01-30 08:57:35 T-Money   285.6             0

In [127]:


df.head(30)

,,Weight,Steps,Net Calories,Email Address,Hours Slept
Date,User,,,,,
2023-02-03 08:20:55,T-Money,188.2,NaN,-1000,NaN,NaN
2023-02-02 13:46:16,T-Money,188.6,NaN,-1000,NaN,NaN
2023-02-01 16:51:27,T-Money,197.8,NaN,-1000,NaN,NaN
2023-01-31 19:13:28,T-Money,188.8,NaN,1200,NaN,NaN
2023-01-30 08:57:35,T-Money,185.6,NaN,0,NaN,NaN
2023-01-29 09:27:56,T-Money,186.6,NaN,-500,NaN,NaN
2023-01-28 08:23:43,T-Money,186.0,NaN,-500,NaN,NaN
2023-01-27 08:56:07,T-Money,186.4,NaN,-1000,NaN,NaN
2023-01-26 08:22:19,T-Money,187.2,NaN,-1000,NaN,NaN
2023-01-25 08:17:04,T-Money,186.2,NaN,-1000,NaN,NaN
2023-01-24 07:28:40,T-Money,187.2,NaN,-500,NaN,NaN
2023-01-23 07:36:42,T-Money,188.8,NaN,-500,NaN,NaN
2023-01-22 08:58:23,T-Money,188.2,NaN,-500,NaN,NaN
2023-01-21 09:49:49,T-Money,189.0,NaN,-500,NaN,NaN
2023-01-20 08:19:14,T-Money,189.8,NaN,-1000,NaN,NaN
2023-01-19 08:19:14,T-Money,NaN,NaN,-1000,NaN,NaN
2023-01-18 08:08:49,T-Money,192.2,NaN,-300,NaN,NaN
2023-01-17 08:15:34,T-Money,191.0,NaN,-500,NaN,NaN
2023-01-16 10:18:53,T-Money,188.8,NaN,-500,NaN,NaN
2023-01-15 08:29:53,T-Money,188.4,NaN,-680,NaN,NaN
2023-01-14 08:55:12,T-Money,189.0,NaN,-500,NaN,NaN
2023-01-13 07:40:26,T-Money,189.8,NaN,-1000,NaN,NaN
2023-01-12 16:39:51,T-Money,192.6,NaN,-1000,NaN,NaN
2023-01-11 08:06:53,T-Money,191.0,NaN,-1000,NaN,NaN
2023-01-10 16:24:08,T-Money,191.6,NaN,-1000,NaN,NaN
2023-01-09 08:40:37,T-Money,190.4,NaN,-500,NaN,NaN
2023-01-08 09:14:55,T-Money,191.6,NaN,-500,NaN,NaN
2023-01-07 10:20:15,T-Money,191.6,NaN,0,NaN,NaN
2023-01-06 07:37:59,T-Money,190.2,NaN,-450,NaN,NaN
2023-01-05 11:21:46,T-Money,192.2,NaN,200,NaN,NaN

In [128]:
# compare to code in next cell
# this is using pythons indexing(?) notation
df.loc[0:3,'Weight']

UnsortedIndexError: 'Key length (1) was greater than MultiIndex lexsort depth (0)'

In [ ]:
# show all rows where the user = "T-Money"
df.loc[df["User"]=="T-Money"]

In [ ]:
# this is passing a list of multiple integers. note how it is only puling row 0 and 3
df.loc[[0,3],'Weight']

In [ ]:
df["Weight"].value_counts(dropna=False)

In [ ]:
df.info()

In [ ]:
df.loc[0:3,"User"]

In [ ]:
df.loc[0:2]

In [ ]:
sns.despine()
sns.set_style('white')
sns.set_palette("BrBG")
df = df.loc[df['User'] == "T-Money"]
df = df.loc[df['Date'] > dt.date(2022,10,1)]

df_graph = sns.lineplot(
    data=df,
    x="Date", 
    y="Weight"
)

df_graph.set_ylim(180, 200)
plt.legend(labels=['T-Money'])
plt.xticks(rotation=45)
plt.yticks(range(180,200,5))
plt.xlim(dt.date(2022, 10, 14), dt.date.today());

In [ ]:
df2.head(100)